version: "3.5"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    environment:
      AGENT_SECRET: da0daishe8ieT5noos6Kaes6Ielu5eeW
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer
    ports:
      - 9000:9000

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer:
    driver: bridge
    name: portainer